# Generated by Django 4.2.11 on 2026-03-18 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom commercial')),
                ('dci', models.CharField(blank=True, max_length=200, verbose_name='DCI')),
                ('forme', models.CharField(max_length=100, verbose_name='Forme galénique')),
                ('dosage', models.CharField(max_length=100, verbose_name='Dosage')),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Prix d'achat")),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix de vente')),
                ('stock_actuel', models.PositiveIntegerField(default=0, verbose_name='Stock actuel')),
                ('stock_minimum', models.PositiveIntegerField(default=10, verbose_name='Stock minimum')),
                ('date_expiration', models.DateField(verbose_name="Date d'expiration")),
                ('ordonnance_requise', models.BooleanField(default=False, verbose_name='Ordonnance requise')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicaments', to='categories.categorie', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Médicament',
                'verbose_name_plural': 'Médicaments',
                'ordering': ['nom'],
            },
        ),
    ]
